package admin

import (
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	"github.com/shopware/shopware-lsp/internal/parser/cst"
)

const meteorPackagePath = "@shopware-ag/meteor-component-library"

var meteorEventListenerPattern = regexp.MustCompile(
	`(?m)^\s*(?:"(on[^"]+)"|(on[A-Za-z][A-Za-z0-9_:-]*))\?\s*:`,
)

var meteorLiteralTypeAliasPattern = regexp.MustCompile(
	`(?m)^\s*(?:export\s+)?type\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*([^;\n]+)\s*;`,
)

type typeDeclarationField struct {
	name        string
	value       string
	optional    bool
	offset      int
	valueOffset int
	quoted      bool
}

// parseMeteorDeclaration consumes the public declarations generated by
// vue-tsc for a Meteor component. Meteor ships these files as its canonical
// component API, while node_modules remains excluded from normal indexing.
func parseMeteorDeclaration(
	filePath,
	source string,
) *VueComponent {
	base := filepath.Base(filePath)
	if !strings.HasPrefix(base, "Mt") || !strings.HasSuffix(base, ".d.ts") {
		return nil
	}
	name := CamelToKebab(strings.TrimSuffix(base, ".d.ts"))
	if name == "" {
		return nil
	}
	lineIndex := cst.NewLineIndex(source)
	component := &VueComponent{
		Name: name, Kind: ComponentRegister, FilePath: filePath,
		DefinitionPath: filePath, Line: 1,
	}
	literalAliases := meteorLiteralTypeAliases(source)

	if open := declarationObjectStart(source, "type __VLS_Props ="); open >= 0 {
		for _, field := range parseTypeDeclarationFields(source, open) {
			line, _ := lineIndex.Position(uint32(field.offset))
			if event := meteorEventName(field.name); event != "" {
				component.Emits = appendUnique(component.Emits, event)
				component.Events = appendComponentEvent(
					component.Events,
					VueComponentEvent{
						Name: event, Type: strings.TrimSpace(field.value),
						Documentation: adminTypeFieldDocumentation(
							source, field.offset,
						),
						FilePath: filePath, Line: int(line) + 1,
						NameRange: typeDeclarationFieldNameRange(
							field, lineIndex, 0,
						),
					},
				)
				continue
			}
			prop := VueComponentProp{
				Name: field.name, Type: strings.TrimSpace(field.value),
				Documentation: adminTypeFieldDocumentation(source, field.offset),
				Required:      !field.optional, FilePath: filePath,
				Line: int(line) + 1,
				NameRange: typeDeclarationFieldNameRange(
					field, lineIndex, 0,
				),
			}
			prop.AllowedValues, prop.AllowedValuesComplete =
				meteorPropAllowedValues(prop.Type, literalAliases)
			component.Props = append(component.Props, prop)
		}
	} else if open := declarationObjectStart(source, "ExtractPropTypes<"); open >= 0 {
		for _, field := range parseTypeDeclarationFields(source, open) {
			line, _ := lineIndex.Position(uint32(field.offset))
			prop := VueComponentProp{
				Name: field.name, FilePath: filePath, Line: int(line) + 1,
				Documentation: adminTypeFieldDocumentation(source, field.offset),
				NameRange: typeDeclarationFieldNameRange(
					field, lineIndex, 0,
				),
			}
			applyRuntimePropDeclaration(&prop, field.value)
			prop.AllowedValues, prop.AllowedValuesComplete =
				meteorPropAllowedValues(prop.Type, literalAliases)
			component.Props = append(component.Props, prop)
		}
	}

	if open := meteorSlotsObjectStart(source); open >= 0 {
		for _, field := range parseTypeDeclarationFields(source, open) {
			line, _ := lineIndex.Position(uint32(field.offset))
			slot := VueComponentSlot{
				Name: field.name, Line: int(line) + 1, FilePath: filePath,
				NameRange:   typeDeclarationFieldNameRange(field, lineIndex, 0),
				PayloadType: meteorSlotPayloadType(field.value), MembersComplete: true,
			}
			if openPayload := strings.IndexByte(slot.PayloadType, '{'); openPayload >= 0 {
				payloadOffset := field.offset
				if relative := strings.Index(
					source[field.offset:], slot.PayloadType,
				); relative >= 0 {
					payloadOffset += relative
				}
				for _, member := range parseTypeDeclarationFields(
					slot.PayloadType,
					openPayload,
				) {
					memberLine, _ := lineIndex.Position(uint32(
						payloadOffset + member.offset,
					))
					slot.Members = appendSlotMember(
						slot.Members,
						VueComponentSlotMember{
							Name: member.name, Type: strings.TrimSpace(member.value),
							FilePath: filePath, Line: int(memberLine) + 1,
							NameRange: typeDeclarationFieldNameRange(
								member, lineIndex, payloadOffset,
							),
						},
					)
				}
			}
			component.Slots = append(component.Slots, slot)
		}
		// Slot navigation has no Twig source for package components. Point it
		// at the declaration that owns the slot instead.
		component.TemplatePath = filePath
	}
	for _, match := range meteorEventListenerPattern.FindAllStringSubmatchIndex(source, -1) {
		listenerStart, listenerEnd := match[2], match[3]
		if listenerStart < 0 {
			listenerStart, listenerEnd = match[4], match[5]
		}
		if listenerStart < 0 || listenerEnd < listenerStart {
			continue
		}
		listener := source[listenerStart:listenerEnd]
		if event := meteorEventName(listener); event != "" {
			component.Emits = appendUnique(component.Emits, event)
			line, _ := lineIndex.Position(uint32(listenerStart))
			component.Events = appendComponentEvent(
				component.Events,
				VueComponentEvent{
					Name: event,
					Documentation: adminTypeFieldDocumentation(
						source, listenerStart,
					),
					FilePath: filePath, Line: int(line) + 1,
					NameRange: sourceRangeAt(
						lineIndex, uint32(listenerStart),
						uint32(listenerEnd),
						isAdminTypeIdentifier(listener),
					),
				},
			)
		}
	}
	applyMeteorRuntimePropCompatibility(component)
	return component
}

func meteorLiteralTypeAliases(source string) map[string][]string {
	result := make(map[string][]string)
	for _, match := range meteorLiteralTypeAliasPattern.FindAllStringSubmatch(source, -1) {
		if len(match) < 3 {
			continue
		}
		values, complete := vueStringLiteralUnionValues(match[2])
		if complete && len(values) > 0 {
			result[match[1]] = values
		}
	}
	return result
}

func meteorPropAllowedValues(
	value string,
	aliases map[string][]string,
) ([]string, bool) {
	value = VuePropValueType(value)
	if strings.TrimSpace(value) == "" {
		return nil, false
	}
	var values []string
	complete := true
	for _, branch := range splitAdminTypeTopLevel(value, '|') {
		branch = trimAdminTypeParentheses(strings.TrimSpace(branch))
		switch branch {
		case "null", "undefined", "void", "never":
			continue
		}
		if literal, found := decodeAdminTypeStringLiteral(branch); found {
			values = appendAllowedValue(values, literal)
			continue
		}
		if aliasValues := aliases[branch]; len(aliasValues) > 0 {
			for _, aliasValue := range aliasValues {
				values = appendAllowedValue(values, aliasValue)
			}
			continue
		}
		complete = false
	}
	return values, complete && len(values) > 0
}

// applyMeteorRuntimePropCompatibility preserves public inputs which Meteor
// intentionally accepts at runtime even though its generated vue-tsc
// declaration is narrower. These are not arbitrary relaxations: mt-link
// forwards `to` to router-link and Shopware core passes both route-location
// objects and URLs, while mt-icon explicitly normalizes numeric sizes to px.
// Keeping the compatibility at the indexed contract source makes completion,
// hover, navigation, and diagnostics agree on the same effective API.
func applyMeteorRuntimePropCompatibility(component *VueComponent) {
	if component == nil {
		return
	}
	for index := range component.Props {
		prop := &component.Props[index]
		switch component.Name + "." + prop.Name {
		case "mt-link.to":
			prop.Type = mergeVueTypes(prop.Type, "object")
		case "mt-icon.size":
			prop.Type = mergeVueTypes(prop.Type, "number")
		}
	}
}

func meteorSlotPayloadType(value string) string {
	value = strings.TrimSpace(value)
	if value == "" || value == "null" || value == "void" {
		return ""
	}
	if strings.HasPrefix(value, "(") {
		if close := matchingSlotDelimiter(value, 0, '(', ')'); close >= 0 {
			parameter := strings.TrimSpace(value[1:close])
			if parameter == "" {
				return ""
			}
			if first := splitSlotTopLevel(parameter, ','); len(first) > 0 {
				parameter = strings.TrimSpace(first[0])
			}
			if colon := indexSlotTopLevel(parameter, ':'); colon >= 0 {
				return strings.TrimSpace(parameter[colon+1:])
			}
			return ""
		}
	}
	if open := strings.IndexByte(value, '{'); open >= 0 {
		if close := balancedBraceEnd(value, open); close >= open {
			return strings.TrimSpace(value[open : close+1])
		}
	}
	return value
}

func declarationObjectStart(source, marker string) int {
	markerOffset := strings.Index(source, marker)
	if markerOffset < 0 {
		return -1
	}
	relative := strings.IndexByte(source[markerOffset+len(marker):], '{')
	if relative < 0 {
		return -1
	}
	return markerOffset + len(marker) + relative
}

func meteorSlotsObjectStart(source string) int {
	for _, marker := range []string{"slots: Readonly<", "slots:"} {
		if open := declarationObjectStart(source, marker); open >= 0 {
			return open
		}
	}
	return -1
}

func parseTypeDeclarationFields(source string, open int) []typeDeclarationField {
	close := balancedBraceEnd(source, open)
	if close < 0 {
		return nil
	}
	body := source[open+1 : close]
	baseOffset := open + 1
	segments := splitTopLevelDeclarations(body, baseOffset)
	fields := make([]typeDeclarationField, 0, len(segments))
	for _, segment := range segments {
		field, ok := parseTypeDeclarationField(segment.text, segment.offset)
		if ok {
			fields = append(fields, field)
		}
	}
	return fields
}

type declarationSegment struct {
	text   string
	offset int
}

func splitTopLevelDeclarations(body string, baseOffset int) []declarationSegment {
	var result []declarationSegment
	start := 0
	state := declarationScanState{}
	for index := 0; index < len(body); index++ {
		state.consume(body, &index)
		if state.inLiteralOrComment() {
			continue
		}
		switch body[index] {
		case '{':
			state.braces++
		case '}':
			state.braces--
		case '(':
			state.parens++
		case ')':
			state.parens--
		case '[':
			state.brackets++
		case ']':
			state.brackets--
		case '<':
			state.angles++
		case '>':
			if state.angles > 0 {
				state.angles--
			}
		case ';', ',':
			if state.braces == 0 && state.parens == 0 && state.brackets == 0 &&
				state.angles == 0 {
				result = append(result, declarationSegment{
					text: body[start:index], offset: baseOffset + start,
				})
				start = index + 1
			}
		}
	}
	if strings.TrimSpace(body[start:]) != "" {
		result = append(result, declarationSegment{
			text: body[start:], offset: baseOffset + start,
		})
	}
	return result
}

type declarationScanState struct {
	quote                    byte
	escaped                  bool
	lineComment              bool
	blockComment             bool
	braces, parens, brackets int
	angles                   int
}

func (state *declarationScanState) inLiteralOrComment() bool {
	return state.quote != 0 || state.lineComment || state.blockComment
}

func (state *declarationScanState) consume(source string, index *int) {
	current := source[*index]
	if state.lineComment {
		if current == '\n' {
			state.lineComment = false
		}
		return
	}
	if state.blockComment {
		if current == '*' && *index+1 < len(source) && source[*index+1] == '/' {
			state.blockComment = false
			*index++
		}
		return
	}
	if state.quote != 0 {
		if state.escaped {
			state.escaped = false
			return
		}
		if current == '\\' {
			state.escaped = true
			return
		}
		if current == state.quote {
			state.quote = 0
		}
		return
	}
	if current == '/' && *index+1 < len(source) {
		switch source[*index+1] {
		case '/':
			state.lineComment = true
			*index++
			return
		case '*':
			state.blockComment = true
			*index++
			return
		}
	}
	if current == '\'' || current == '"' || current == '`' {
		state.quote = current
	}
}

func balancedBraceEnd(source string, open int) int {
	if open < 0 || open >= len(source) || source[open] != '{' {
		return -1
	}
	depth := 0
	state := declarationScanState{}
	for index := open; index < len(source); index++ {
		state.consume(source, &index)
		if state.inLiteralOrComment() {
			continue
		}
		switch source[index] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return index
			}
		}
	}
	return -1
}

func parseTypeDeclarationField(text string, absoluteOffset int) (typeDeclarationField, bool) {
	trimmed, skipped := trimDeclarationPrefix(text)
	if trimmed == "" {
		return typeDeclarationField{}, false
	}
	nameEnd := declarationNameEnd(trimmed)
	if nameEnd <= 0 {
		return typeDeclarationField{}, false
	}
	rawName := strings.TrimSpace(trimmed[:nameEnd])
	optional := strings.HasSuffix(rawName, "?")
	rawName = strings.TrimSpace(strings.TrimSuffix(rawName, "?"))
	rawName = strings.TrimPrefix(rawName, "readonly ")
	name := strings.Trim(rawName, "'\"")
	if name == "" || strings.ContainsAny(name, " \t\r\n") {
		return typeDeclarationField{}, false
	}
	valueStart := nameEnd
	for valueStart < len(trimmed) &&
		(trimmed[valueStart] == '?' || trimmed[valueStart] == ' ' ||
			trimmed[valueStart] == '\t') {
		valueStart++
	}
	value := ""
	valueOffset := -1
	if valueStart < len(trimmed) && trimmed[valueStart] == ':' {
		valueOffset = valueStart + 1
		for valueOffset < len(trimmed) &&
			unicode.IsSpace(rune(trimmed[valueOffset])) {
			valueOffset++
		}
		value = strings.TrimSpace(trimmed[valueOffset:])
	} else if valueStart < len(trimmed) && trimmed[valueStart] == '(' {
		valueOffset = valueStart
		value = strings.TrimSpace(trimmed[valueOffset:])
	}
	nameOffset := strings.Index(trimmed, rawName)
	if nameOffset < 0 {
		nameOffset = 0
	}
	absoluteValueOffset := -1
	if valueOffset >= 0 {
		absoluteValueOffset = absoluteOffset + skipped + valueOffset
	}
	return typeDeclarationField{
		name: name, value: value, optional: optional,
		offset:      absoluteOffset + skipped + nameOffset,
		valueOffset: absoluteValueOffset,
		quoted: len(rawName) >= 2 &&
			(rawName[0] == '\'' || rawName[0] == '"') &&
			rawName[len(rawName)-1] == rawName[0],
	}, true
}

func typeDeclarationFieldNameRange(
	field typeDeclarationField,
	lineIndex *cst.LineIndex,
	baseOffset int,
) AdminSourceRange {
	if lineIndex == nil || field.name == "" || field.offset < 0 || baseOffset < 0 {
		return AdminSourceRange{}
	}
	start := baseOffset + field.offset
	if field.quoted {
		start++
	}
	end := start + len(field.name)
	return sourceRangeAt(
		lineIndex, uint32(start), uint32(end), !field.quoted,
	)
}

func trimDeclarationPrefix(text string) (string, int) {
	offset := 0
	for {
		trimmed := strings.TrimLeftFunc(text[offset:], unicode.IsSpace)
		offset += len(text[offset:]) - len(trimmed)
		if strings.HasPrefix(trimmed, "/**") || strings.HasPrefix(trimmed, "/*") {
			end := strings.Index(trimmed, "*/")
			if end < 0 {
				return "", len(text)
			}
			offset += end + 2
			continue
		}
		if strings.HasPrefix(trimmed, "//") {
			end := strings.IndexByte(trimmed, '\n')
			if end < 0 {
				return "", len(text)
			}
			offset += end + 1
			continue
		}
		return trimmed, offset
	}
}

func declarationNameEnd(text string) int {
	quote := byte(0)
	escaped := false
	for index := 0; index < len(text); index++ {
		current := text[index]
		if quote != 0 {
			if escaped {
				escaped = false
				continue
			}
			if current == '\\' {
				escaped = true
				continue
			}
			if current == quote {
				quote = 0
			}
			continue
		}
		if current == '\'' || current == '"' {
			quote = current
			continue
		}
		if current == ':' || current == '(' {
			return index
		}
	}
	return -1
}

func applyRuntimePropDeclaration(prop *VueComponentProp, value string) {
	open := strings.IndexByte(value, '{')
	if prop == nil || open < 0 {
		return
	}
	fields := parseTypeDeclarationFields(value, open)
	for _, field := range fields {
		switch field.name {
		case "type":
			prop.Type = meteorRuntimeType(field.value)
		case "required":
			prop.Required = strings.TrimSpace(field.value) == "true"
		}
	}
}

func meteorRuntimeType(value string) string {
	value = strings.TrimSpace(value)
	if start := strings.Index(value, "PropType<"); start >= 0 {
		inner := value[start+len("PropType<"):]
		if end := strings.LastIndexByte(inner, '>'); end >= 0 {
			return strings.TrimSpace(inner[:end])
		}
	}
	value = strings.TrimSuffix(value, "Constructor")
	switch value {
	case "String":
		return "String"
	case "Boolean":
		return "Boolean"
	case "Number":
		return "Number"
	case "Object":
		return "Object"
	case "Array":
		return "Array"
	case "Function":
		return "Function"
	default:
		return value
	}
}

func meteorEventName(listener string) string {
	if !strings.HasPrefix(listener, "on") || len(listener) <= 2 {
		return ""
	}
	event := listener[2:]
	if event[0] < 'A' || event[0] > 'Z' {
		return ""
	}
	event = strings.ToLower(event[:1]) + event[1:]
	return CamelToKebab(event)
}

func appendUnique(values []string, value string) []string {
	if value == "" {
		return values
	}
	for _, existing := range values {
		if existing == value {
			return values
		}
	}
	return append(values, value)
}
