// Code generated by gen.go; DO NOT EDIT.

package ast

import "github.com/shopware/shopware-lsp/internal/parser/twig/syntax"

// Body is a typed wrapper around a syntax.Body node.
type Body struct{ n *syntax.Node }

// CastBody returns a typed Body wrapper if n has kind syntax.Body.
func CastBody(n *syntax.Node) (Body, bool) {
	if n == nil || n.Kind() != syntax.Body {
		return Body{}, false
	}
	return Body{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x Body) Syntax() *syntax.Node { return x.n }

// TwigVar is a typed wrapper around a syntax.TwigVar node.
type TwigVar struct{ n *syntax.Node }

// CastTwigVar returns a typed TwigVar wrapper if n has kind syntax.TwigVar.
func CastTwigVar(n *syntax.Node) (TwigVar, bool) {
	if n == nil || n.Kind() != syntax.TwigVar {
		return TwigVar{}, false
	}
	return TwigVar{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigVar) Syntax() *syntax.Node { return x.n }

// TwigExpression is a typed wrapper around a syntax.TwigExpression node.
type TwigExpression struct{ n *syntax.Node }

// CastTwigExpression returns a typed TwigExpression wrapper if n has kind syntax.TwigExpression.
func CastTwigExpression(n *syntax.Node) (TwigExpression, bool) {
	if n == nil || n.Kind() != syntax.TwigExpression {
		return TwigExpression{}, false
	}
	return TwigExpression{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigExpression) Syntax() *syntax.Node { return x.n }

// TwigBinaryExpression is a typed wrapper around a syntax.TwigBinaryExpression node.
type TwigBinaryExpression struct{ n *syntax.Node }

// CastTwigBinaryExpression returns a typed TwigBinaryExpression wrapper if n has kind syntax.TwigBinaryExpression.
func CastTwigBinaryExpression(n *syntax.Node) (TwigBinaryExpression, bool) {
	if n == nil || n.Kind() != syntax.TwigBinaryExpression {
		return TwigBinaryExpression{}, false
	}
	return TwigBinaryExpression{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigBinaryExpression) Syntax() *syntax.Node { return x.n }

// TwigUnaryExpression is a typed wrapper around a syntax.TwigUnaryExpression node.
type TwigUnaryExpression struct{ n *syntax.Node }

// CastTwigUnaryExpression returns a typed TwigUnaryExpression wrapper if n has kind syntax.TwigUnaryExpression.
func CastTwigUnaryExpression(n *syntax.Node) (TwigUnaryExpression, bool) {
	if n == nil || n.Kind() != syntax.TwigUnaryExpression {
		return TwigUnaryExpression{}, false
	}
	return TwigUnaryExpression{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigUnaryExpression) Syntax() *syntax.Node { return x.n }

// TwigParenthesesExpression is a typed wrapper around a syntax.TwigParenthesesExpression node.
type TwigParenthesesExpression struct{ n *syntax.Node }

// CastTwigParenthesesExpression returns a typed TwigParenthesesExpression wrapper if n has kind syntax.TwigParenthesesExpression.
func CastTwigParenthesesExpression(n *syntax.Node) (TwigParenthesesExpression, bool) {
	if n == nil || n.Kind() != syntax.TwigParenthesesExpression {
		return TwigParenthesesExpression{}, false
	}
	return TwigParenthesesExpression{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigParenthesesExpression) Syntax() *syntax.Node { return x.n }

// TwigConditionalExpression is a typed wrapper around a syntax.TwigConditionalExpression node.
type TwigConditionalExpression struct{ n *syntax.Node }

// CastTwigConditionalExpression returns a typed TwigConditionalExpression wrapper if n has kind syntax.TwigConditionalExpression.
func CastTwigConditionalExpression(n *syntax.Node) (TwigConditionalExpression, bool) {
	if n == nil || n.Kind() != syntax.TwigConditionalExpression {
		return TwigConditionalExpression{}, false
	}
	return TwigConditionalExpression{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigConditionalExpression) Syntax() *syntax.Node { return x.n }

// TwigOperand is a typed wrapper around a syntax.TwigOperand node.
type TwigOperand struct{ n *syntax.Node }

// CastTwigOperand returns a typed TwigOperand wrapper if n has kind syntax.TwigOperand.
func CastTwigOperand(n *syntax.Node) (TwigOperand, bool) {
	if n == nil || n.Kind() != syntax.TwigOperand {
		return TwigOperand{}, false
	}
	return TwigOperand{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigOperand) Syntax() *syntax.Node { return x.n }

// TwigAccessor is a typed wrapper around a syntax.TwigAccessor node.
type TwigAccessor struct{ n *syntax.Node }

// CastTwigAccessor returns a typed TwigAccessor wrapper if n has kind syntax.TwigAccessor.
func CastTwigAccessor(n *syntax.Node) (TwigAccessor, bool) {
	if n == nil || n.Kind() != syntax.TwigAccessor {
		return TwigAccessor{}, false
	}
	return TwigAccessor{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigAccessor) Syntax() *syntax.Node { return x.n }

// TwigFilter is a typed wrapper around a syntax.TwigFilter node.
type TwigFilter struct{ n *syntax.Node }

// CastTwigFilter returns a typed TwigFilter wrapper if n has kind syntax.TwigFilter.
func CastTwigFilter(n *syntax.Node) (TwigFilter, bool) {
	if n == nil || n.Kind() != syntax.TwigFilter {
		return TwigFilter{}, false
	}
	return TwigFilter{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigFilter) Syntax() *syntax.Node { return x.n }

// TwigIndexLookup is a typed wrapper around a syntax.TwigIndexLookup node.
type TwigIndexLookup struct{ n *syntax.Node }

// CastTwigIndexLookup returns a typed TwigIndexLookup wrapper if n has kind syntax.TwigIndexLookup.
func CastTwigIndexLookup(n *syntax.Node) (TwigIndexLookup, bool) {
	if n == nil || n.Kind() != syntax.TwigIndexLookup {
		return TwigIndexLookup{}, false
	}
	return TwigIndexLookup{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIndexLookup) Syntax() *syntax.Node { return x.n }

// TwigIndex is a typed wrapper around a syntax.TwigIndex node.
type TwigIndex struct{ n *syntax.Node }

// CastTwigIndex returns a typed TwigIndex wrapper if n has kind syntax.TwigIndex.
func CastTwigIndex(n *syntax.Node) (TwigIndex, bool) {
	if n == nil || n.Kind() != syntax.TwigIndex {
		return TwigIndex{}, false
	}
	return TwigIndex{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIndex) Syntax() *syntax.Node { return x.n }

// TwigIndexRange is a typed wrapper around a syntax.TwigIndexRange node.
type TwigIndexRange struct{ n *syntax.Node }

// CastTwigIndexRange returns a typed TwigIndexRange wrapper if n has kind syntax.TwigIndexRange.
func CastTwigIndexRange(n *syntax.Node) (TwigIndexRange, bool) {
	if n == nil || n.Kind() != syntax.TwigIndexRange {
		return TwigIndexRange{}, false
	}
	return TwigIndexRange{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIndexRange) Syntax() *syntax.Node { return x.n }

// TwigFunctionCall is a typed wrapper around a syntax.TwigFunctionCall node.
type TwigFunctionCall struct{ n *syntax.Node }

// CastTwigFunctionCall returns a typed TwigFunctionCall wrapper if n has kind syntax.TwigFunctionCall.
func CastTwigFunctionCall(n *syntax.Node) (TwigFunctionCall, bool) {
	if n == nil || n.Kind() != syntax.TwigFunctionCall {
		return TwigFunctionCall{}, false
	}
	return TwigFunctionCall{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigFunctionCall) Syntax() *syntax.Node { return x.n }

// TwigArrowFunction is a typed wrapper around a syntax.TwigArrowFunction node.
type TwigArrowFunction struct{ n *syntax.Node }

// CastTwigArrowFunction returns a typed TwigArrowFunction wrapper if n has kind syntax.TwigArrowFunction.
func CastTwigArrowFunction(n *syntax.Node) (TwigArrowFunction, bool) {
	if n == nil || n.Kind() != syntax.TwigArrowFunction {
		return TwigArrowFunction{}, false
	}
	return TwigArrowFunction{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigArrowFunction) Syntax() *syntax.Node { return x.n }

// TwigArguments is a typed wrapper around a syntax.TwigArguments node.
type TwigArguments struct{ n *syntax.Node }

// CastTwigArguments returns a typed TwigArguments wrapper if n has kind syntax.TwigArguments.
func CastTwigArguments(n *syntax.Node) (TwigArguments, bool) {
	if n == nil || n.Kind() != syntax.TwigArguments {
		return TwigArguments{}, false
	}
	return TwigArguments{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigArguments) Syntax() *syntax.Node { return x.n }

// TwigNamedArgument is a typed wrapper around a syntax.TwigNamedArgument node.
type TwigNamedArgument struct{ n *syntax.Node }

// CastTwigNamedArgument returns a typed TwigNamedArgument wrapper if n has kind syntax.TwigNamedArgument.
func CastTwigNamedArgument(n *syntax.Node) (TwigNamedArgument, bool) {
	if n == nil || n.Kind() != syntax.TwigNamedArgument {
		return TwigNamedArgument{}, false
	}
	return TwigNamedArgument{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigNamedArgument) Syntax() *syntax.Node { return x.n }

// TwigLiteralString is a typed wrapper around a syntax.TwigLiteralString node.
type TwigLiteralString struct{ n *syntax.Node }

// CastTwigLiteralString returns a typed TwigLiteralString wrapper if n has kind syntax.TwigLiteralString.
func CastTwigLiteralString(n *syntax.Node) (TwigLiteralString, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralString {
		return TwigLiteralString{}, false
	}
	return TwigLiteralString{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralString) Syntax() *syntax.Node { return x.n }

// TwigLiteralStringInner is a typed wrapper around a syntax.TwigLiteralStringInner node.
type TwigLiteralStringInner struct{ n *syntax.Node }

// CastTwigLiteralStringInner returns a typed TwigLiteralStringInner wrapper if n has kind syntax.TwigLiteralStringInner.
func CastTwigLiteralStringInner(n *syntax.Node) (TwigLiteralStringInner, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralStringInner {
		return TwigLiteralStringInner{}, false
	}
	return TwigLiteralStringInner{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralStringInner) Syntax() *syntax.Node { return x.n }

// TwigLiteralStringInterpolation is a typed wrapper around a syntax.TwigLiteralStringInterpolation node.
type TwigLiteralStringInterpolation struct{ n *syntax.Node }

// CastTwigLiteralStringInterpolation returns a typed TwigLiteralStringInterpolation wrapper if n has kind syntax.TwigLiteralStringInterpolation.
func CastTwigLiteralStringInterpolation(n *syntax.Node) (TwigLiteralStringInterpolation, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralStringInterpolation {
		return TwigLiteralStringInterpolation{}, false
	}
	return TwigLiteralStringInterpolation{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralStringInterpolation) Syntax() *syntax.Node { return x.n }

// TwigLiteralNumber is a typed wrapper around a syntax.TwigLiteralNumber node.
type TwigLiteralNumber struct{ n *syntax.Node }

// CastTwigLiteralNumber returns a typed TwigLiteralNumber wrapper if n has kind syntax.TwigLiteralNumber.
func CastTwigLiteralNumber(n *syntax.Node) (TwigLiteralNumber, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralNumber {
		return TwigLiteralNumber{}, false
	}
	return TwigLiteralNumber{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralNumber) Syntax() *syntax.Node { return x.n }

// TwigLiteralArray is a typed wrapper around a syntax.TwigLiteralArray node.
type TwigLiteralArray struct{ n *syntax.Node }

// CastTwigLiteralArray returns a typed TwigLiteralArray wrapper if n has kind syntax.TwigLiteralArray.
func CastTwigLiteralArray(n *syntax.Node) (TwigLiteralArray, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralArray {
		return TwigLiteralArray{}, false
	}
	return TwigLiteralArray{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralArray) Syntax() *syntax.Node { return x.n }

// TwigLiteralArrayInner is a typed wrapper around a syntax.TwigLiteralArrayInner node.
type TwigLiteralArrayInner struct{ n *syntax.Node }

// CastTwigLiteralArrayInner returns a typed TwigLiteralArrayInner wrapper if n has kind syntax.TwigLiteralArrayInner.
func CastTwigLiteralArrayInner(n *syntax.Node) (TwigLiteralArrayInner, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralArrayInner {
		return TwigLiteralArrayInner{}, false
	}
	return TwigLiteralArrayInner{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralArrayInner) Syntax() *syntax.Node { return x.n }

// TwigLiteralNull is a typed wrapper around a syntax.TwigLiteralNull node.
type TwigLiteralNull struct{ n *syntax.Node }

// CastTwigLiteralNull returns a typed TwigLiteralNull wrapper if n has kind syntax.TwigLiteralNull.
func CastTwigLiteralNull(n *syntax.Node) (TwigLiteralNull, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralNull {
		return TwigLiteralNull{}, false
	}
	return TwigLiteralNull{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralNull) Syntax() *syntax.Node { return x.n }

// TwigLiteralBoolean is a typed wrapper around a syntax.TwigLiteralBoolean node.
type TwigLiteralBoolean struct{ n *syntax.Node }

// CastTwigLiteralBoolean returns a typed TwigLiteralBoolean wrapper if n has kind syntax.TwigLiteralBoolean.
func CastTwigLiteralBoolean(n *syntax.Node) (TwigLiteralBoolean, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralBoolean {
		return TwigLiteralBoolean{}, false
	}
	return TwigLiteralBoolean{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralBoolean) Syntax() *syntax.Node { return x.n }

// TwigLiteralHash is a typed wrapper around a syntax.TwigLiteralHash node.
type TwigLiteralHash struct{ n *syntax.Node }

// CastTwigLiteralHash returns a typed TwigLiteralHash wrapper if n has kind syntax.TwigLiteralHash.
func CastTwigLiteralHash(n *syntax.Node) (TwigLiteralHash, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralHash {
		return TwigLiteralHash{}, false
	}
	return TwigLiteralHash{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralHash) Syntax() *syntax.Node { return x.n }

// TwigLiteralHashItems is a typed wrapper around a syntax.TwigLiteralHashItems node.
type TwigLiteralHashItems struct{ n *syntax.Node }

// CastTwigLiteralHashItems returns a typed TwigLiteralHashItems wrapper if n has kind syntax.TwigLiteralHashItems.
func CastTwigLiteralHashItems(n *syntax.Node) (TwigLiteralHashItems, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralHashItems {
		return TwigLiteralHashItems{}, false
	}
	return TwigLiteralHashItems{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralHashItems) Syntax() *syntax.Node { return x.n }

// TwigLiteralHashPair is a typed wrapper around a syntax.TwigLiteralHashPair node.
type TwigLiteralHashPair struct{ n *syntax.Node }

// CastTwigLiteralHashPair returns a typed TwigLiteralHashPair wrapper if n has kind syntax.TwigLiteralHashPair.
func CastTwigLiteralHashPair(n *syntax.Node) (TwigLiteralHashPair, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralHashPair {
		return TwigLiteralHashPair{}, false
	}
	return TwigLiteralHashPair{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralHashPair) Syntax() *syntax.Node { return x.n }

// TwigLiteralHashKey is a typed wrapper around a syntax.TwigLiteralHashKey node.
type TwigLiteralHashKey struct{ n *syntax.Node }

// CastTwigLiteralHashKey returns a typed TwigLiteralHashKey wrapper if n has kind syntax.TwigLiteralHashKey.
func CastTwigLiteralHashKey(n *syntax.Node) (TwigLiteralHashKey, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralHashKey {
		return TwigLiteralHashKey{}, false
	}
	return TwigLiteralHashKey{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralHashKey) Syntax() *syntax.Node { return x.n }

// TwigLiteralHashValue is a typed wrapper around a syntax.TwigLiteralHashValue node.
type TwigLiteralHashValue struct{ n *syntax.Node }

// CastTwigLiteralHashValue returns a typed TwigLiteralHashValue wrapper if n has kind syntax.TwigLiteralHashValue.
func CastTwigLiteralHashValue(n *syntax.Node) (TwigLiteralHashValue, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralHashValue {
		return TwigLiteralHashValue{}, false
	}
	return TwigLiteralHashValue{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralHashValue) Syntax() *syntax.Node { return x.n }

// TwigLiteralName is a typed wrapper around a syntax.TwigLiteralName node.
type TwigLiteralName struct{ n *syntax.Node }

// CastTwigLiteralName returns a typed TwigLiteralName wrapper if n has kind syntax.TwigLiteralName.
func CastTwigLiteralName(n *syntax.Node) (TwigLiteralName, bool) {
	if n == nil || n.Kind() != syntax.TwigLiteralName {
		return TwigLiteralName{}, false
	}
	return TwigLiteralName{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigLiteralName) Syntax() *syntax.Node { return x.n }

// TwigComment is a typed wrapper around a syntax.TwigComment node.
type TwigComment struct{ n *syntax.Node }

// CastTwigComment returns a typed TwigComment wrapper if n has kind syntax.TwigComment.
func CastTwigComment(n *syntax.Node) (TwigComment, bool) {
	if n == nil || n.Kind() != syntax.TwigComment {
		return TwigComment{}, false
	}
	return TwigComment{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigComment) Syntax() *syntax.Node { return x.n }

// TwigBlock is a typed wrapper around a syntax.TwigBlock node.
type TwigBlock struct{ n *syntax.Node }

// CastTwigBlock returns a typed TwigBlock wrapper if n has kind syntax.TwigBlock.
func CastTwigBlock(n *syntax.Node) (TwigBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigBlock {
		return TwigBlock{}, false
	}
	return TwigBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigBlock) Syntax() *syntax.Node { return x.n }

// TwigStartingBlock is a typed wrapper around a syntax.TwigStartingBlock node.
type TwigStartingBlock struct{ n *syntax.Node }

// CastTwigStartingBlock returns a typed TwigStartingBlock wrapper if n has kind syntax.TwigStartingBlock.
func CastTwigStartingBlock(n *syntax.Node) (TwigStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigStartingBlock {
		return TwigStartingBlock{}, false
	}
	return TwigStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigEndingBlock is a typed wrapper around a syntax.TwigEndingBlock node.
type TwigEndingBlock struct{ n *syntax.Node }

// CastTwigEndingBlock returns a typed TwigEndingBlock wrapper if n has kind syntax.TwigEndingBlock.
func CastTwigEndingBlock(n *syntax.Node) (TwigEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEndingBlock {
		return TwigEndingBlock{}, false
	}
	return TwigEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigIf is a typed wrapper around a syntax.TwigIf node.
type TwigIf struct{ n *syntax.Node }

// CastTwigIf returns a typed TwigIf wrapper if n has kind syntax.TwigIf.
func CastTwigIf(n *syntax.Node) (TwigIf, bool) {
	if n == nil || n.Kind() != syntax.TwigIf {
		return TwigIf{}, false
	}
	return TwigIf{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIf) Syntax() *syntax.Node { return x.n }

// TwigIfBlock is a typed wrapper around a syntax.TwigIfBlock node.
type TwigIfBlock struct{ n *syntax.Node }

// CastTwigIfBlock returns a typed TwigIfBlock wrapper if n has kind syntax.TwigIfBlock.
func CastTwigIfBlock(n *syntax.Node) (TwigIfBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigIfBlock {
		return TwigIfBlock{}, false
	}
	return TwigIfBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIfBlock) Syntax() *syntax.Node { return x.n }

// TwigElseIfBlock is a typed wrapper around a syntax.TwigElseIfBlock node.
type TwigElseIfBlock struct{ n *syntax.Node }

// CastTwigElseIfBlock returns a typed TwigElseIfBlock wrapper if n has kind syntax.TwigElseIfBlock.
func CastTwigElseIfBlock(n *syntax.Node) (TwigElseIfBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigElseIfBlock {
		return TwigElseIfBlock{}, false
	}
	return TwigElseIfBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigElseIfBlock) Syntax() *syntax.Node { return x.n }

// TwigElseBlock is a typed wrapper around a syntax.TwigElseBlock node.
type TwigElseBlock struct{ n *syntax.Node }

// CastTwigElseBlock returns a typed TwigElseBlock wrapper if n has kind syntax.TwigElseBlock.
func CastTwigElseBlock(n *syntax.Node) (TwigElseBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigElseBlock {
		return TwigElseBlock{}, false
	}
	return TwigElseBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigElseBlock) Syntax() *syntax.Node { return x.n }

// TwigEndIfBlock is a typed wrapper around a syntax.TwigEndifBlock node.
type TwigEndIfBlock struct{ n *syntax.Node }

// CastTwigEndIfBlock returns a typed TwigEndIfBlock wrapper if n has kind syntax.TwigEndifBlock.
func CastTwigEndIfBlock(n *syntax.Node) (TwigEndIfBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEndifBlock {
		return TwigEndIfBlock{}, false
	}
	return TwigEndIfBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEndIfBlock) Syntax() *syntax.Node { return x.n }

// TwigSet is a typed wrapper around a syntax.TwigSet node.
type TwigSet struct{ n *syntax.Node }

// CastTwigSet returns a typed TwigSet wrapper if n has kind syntax.TwigSet.
func CastTwigSet(n *syntax.Node) (TwigSet, bool) {
	if n == nil || n.Kind() != syntax.TwigSet {
		return TwigSet{}, false
	}
	return TwigSet{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigSet) Syntax() *syntax.Node { return x.n }

// TwigSetBlock is a typed wrapper around a syntax.TwigSetBlock node.
type TwigSetBlock struct{ n *syntax.Node }

// CastTwigSetBlock returns a typed TwigSetBlock wrapper if n has kind syntax.TwigSetBlock.
func CastTwigSetBlock(n *syntax.Node) (TwigSetBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigSetBlock {
		return TwigSetBlock{}, false
	}
	return TwigSetBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigSetBlock) Syntax() *syntax.Node { return x.n }

// TwigEndSetBlock is a typed wrapper around a syntax.TwigEndsetBlock node.
type TwigEndSetBlock struct{ n *syntax.Node }

// CastTwigEndSetBlock returns a typed TwigEndSetBlock wrapper if n has kind syntax.TwigEndsetBlock.
func CastTwigEndSetBlock(n *syntax.Node) (TwigEndSetBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEndsetBlock {
		return TwigEndSetBlock{}, false
	}
	return TwigEndSetBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEndSetBlock) Syntax() *syntax.Node { return x.n }

// TwigAssignment is a typed wrapper around a syntax.TwigAssignment node.
type TwigAssignment struct{ n *syntax.Node }

// CastTwigAssignment returns a typed TwigAssignment wrapper if n has kind syntax.TwigAssignment.
func CastTwigAssignment(n *syntax.Node) (TwigAssignment, bool) {
	if n == nil || n.Kind() != syntax.TwigAssignment {
		return TwigAssignment{}, false
	}
	return TwigAssignment{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigAssignment) Syntax() *syntax.Node { return x.n }

// TwigFor is a typed wrapper around a syntax.TwigFor node.
type TwigFor struct{ n *syntax.Node }

// CastTwigFor returns a typed TwigFor wrapper if n has kind syntax.TwigFor.
func CastTwigFor(n *syntax.Node) (TwigFor, bool) {
	if n == nil || n.Kind() != syntax.TwigFor {
		return TwigFor{}, false
	}
	return TwigFor{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigFor) Syntax() *syntax.Node { return x.n }

// TwigForBlock is a typed wrapper around a syntax.TwigForBlock node.
type TwigForBlock struct{ n *syntax.Node }

// CastTwigForBlock returns a typed TwigForBlock wrapper if n has kind syntax.TwigForBlock.
func CastTwigForBlock(n *syntax.Node) (TwigForBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigForBlock {
		return TwigForBlock{}, false
	}
	return TwigForBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigForBlock) Syntax() *syntax.Node { return x.n }

// TwigForElseBlock is a typed wrapper around a syntax.TwigForElseBlock node.
type TwigForElseBlock struct{ n *syntax.Node }

// CastTwigForElseBlock returns a typed TwigForElseBlock wrapper if n has kind syntax.TwigForElseBlock.
func CastTwigForElseBlock(n *syntax.Node) (TwigForElseBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigForElseBlock {
		return TwigForElseBlock{}, false
	}
	return TwigForElseBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigForElseBlock) Syntax() *syntax.Node { return x.n }

// TwigEndForBlock is a typed wrapper around a syntax.TwigEndforBlock node.
type TwigEndForBlock struct{ n *syntax.Node }

// CastTwigEndForBlock returns a typed TwigEndForBlock wrapper if n has kind syntax.TwigEndforBlock.
func CastTwigEndForBlock(n *syntax.Node) (TwigEndForBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEndforBlock {
		return TwigEndForBlock{}, false
	}
	return TwigEndForBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEndForBlock) Syntax() *syntax.Node { return x.n }

// TwigExtends is a typed wrapper around a syntax.TwigExtends node.
type TwigExtends struct{ n *syntax.Node }

// CastTwigExtends returns a typed TwigExtends wrapper if n has kind syntax.TwigExtends.
func CastTwigExtends(n *syntax.Node) (TwigExtends, bool) {
	if n == nil || n.Kind() != syntax.TwigExtends {
		return TwigExtends{}, false
	}
	return TwigExtends{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigExtends) Syntax() *syntax.Node { return x.n }

// TwigInclude is a typed wrapper around a syntax.TwigInclude node.
type TwigInclude struct{ n *syntax.Node }

// CastTwigInclude returns a typed TwigInclude wrapper if n has kind syntax.TwigInclude.
func CastTwigInclude(n *syntax.Node) (TwigInclude, bool) {
	if n == nil || n.Kind() != syntax.TwigInclude {
		return TwigInclude{}, false
	}
	return TwigInclude{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigInclude) Syntax() *syntax.Node { return x.n }

// TwigIncludeWith is a typed wrapper around a syntax.TwigIncludeWith node.
type TwigIncludeWith struct{ n *syntax.Node }

// CastTwigIncludeWith returns a typed TwigIncludeWith wrapper if n has kind syntax.TwigIncludeWith.
func CastTwigIncludeWith(n *syntax.Node) (TwigIncludeWith, bool) {
	if n == nil || n.Kind() != syntax.TwigIncludeWith {
		return TwigIncludeWith{}, false
	}
	return TwigIncludeWith{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigIncludeWith) Syntax() *syntax.Node { return x.n }

// TwigUse is a typed wrapper around a syntax.TwigUse node.
type TwigUse struct{ n *syntax.Node }

// CastTwigUse returns a typed TwigUse wrapper if n has kind syntax.TwigUse.
func CastTwigUse(n *syntax.Node) (TwigUse, bool) {
	if n == nil || n.Kind() != syntax.TwigUse {
		return TwigUse{}, false
	}
	return TwigUse{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigUse) Syntax() *syntax.Node { return x.n }

// TwigOverride is a typed wrapper around a syntax.TwigOverride node.
type TwigOverride struct{ n *syntax.Node }

// CastTwigOverride returns a typed TwigOverride wrapper if n has kind syntax.TwigOverride.
func CastTwigOverride(n *syntax.Node) (TwigOverride, bool) {
	if n == nil || n.Kind() != syntax.TwigOverride {
		return TwigOverride{}, false
	}
	return TwigOverride{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigOverride) Syntax() *syntax.Node { return x.n }

// TwigApply is a typed wrapper around a syntax.TwigApply node.
type TwigApply struct{ n *syntax.Node }

// CastTwigApply returns a typed TwigApply wrapper if n has kind syntax.TwigApply.
func CastTwigApply(n *syntax.Node) (TwigApply, bool) {
	if n == nil || n.Kind() != syntax.TwigApply {
		return TwigApply{}, false
	}
	return TwigApply{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigApply) Syntax() *syntax.Node { return x.n }

// TwigApplyStartingBlock is a typed wrapper around a syntax.TwigApplyStartingBlock node.
type TwigApplyStartingBlock struct{ n *syntax.Node }

// CastTwigApplyStartingBlock returns a typed TwigApplyStartingBlock wrapper if n has kind syntax.TwigApplyStartingBlock.
func CastTwigApplyStartingBlock(n *syntax.Node) (TwigApplyStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigApplyStartingBlock {
		return TwigApplyStartingBlock{}, false
	}
	return TwigApplyStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigApplyStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigApplyEndingBlock is a typed wrapper around a syntax.TwigApplyEndingBlock node.
type TwigApplyEndingBlock struct{ n *syntax.Node }

// CastTwigApplyEndingBlock returns a typed TwigApplyEndingBlock wrapper if n has kind syntax.TwigApplyEndingBlock.
func CastTwigApplyEndingBlock(n *syntax.Node) (TwigApplyEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigApplyEndingBlock {
		return TwigApplyEndingBlock{}, false
	}
	return TwigApplyEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigApplyEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigAutoescape is a typed wrapper around a syntax.TwigAutoescape node.
type TwigAutoescape struct{ n *syntax.Node }

// CastTwigAutoescape returns a typed TwigAutoescape wrapper if n has kind syntax.TwigAutoescape.
func CastTwigAutoescape(n *syntax.Node) (TwigAutoescape, bool) {
	if n == nil || n.Kind() != syntax.TwigAutoescape {
		return TwigAutoescape{}, false
	}
	return TwigAutoescape{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigAutoescape) Syntax() *syntax.Node { return x.n }

// TwigAutoescapeStartingBlock is a typed wrapper around a syntax.TwigAutoescapeStartingBlock node.
type TwigAutoescapeStartingBlock struct{ n *syntax.Node }

// CastTwigAutoescapeStartingBlock returns a typed TwigAutoescapeStartingBlock wrapper if n has kind syntax.TwigAutoescapeStartingBlock.
func CastTwigAutoescapeStartingBlock(n *syntax.Node) (TwigAutoescapeStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigAutoescapeStartingBlock {
		return TwigAutoescapeStartingBlock{}, false
	}
	return TwigAutoescapeStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigAutoescapeStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigAutoescapeEndingBlock is a typed wrapper around a syntax.TwigAutoescapeEndingBlock node.
type TwigAutoescapeEndingBlock struct{ n *syntax.Node }

// CastTwigAutoescapeEndingBlock returns a typed TwigAutoescapeEndingBlock wrapper if n has kind syntax.TwigAutoescapeEndingBlock.
func CastTwigAutoescapeEndingBlock(n *syntax.Node) (TwigAutoescapeEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigAutoescapeEndingBlock {
		return TwigAutoescapeEndingBlock{}, false
	}
	return TwigAutoescapeEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigAutoescapeEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigDeprecated is a typed wrapper around a syntax.TwigDeprecated node.
type TwigDeprecated struct{ n *syntax.Node }

// CastTwigDeprecated returns a typed TwigDeprecated wrapper if n has kind syntax.TwigDeprecated.
func CastTwigDeprecated(n *syntax.Node) (TwigDeprecated, bool) {
	if n == nil || n.Kind() != syntax.TwigDeprecated {
		return TwigDeprecated{}, false
	}
	return TwigDeprecated{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigDeprecated) Syntax() *syntax.Node { return x.n }

// TwigDo is a typed wrapper around a syntax.TwigDo node.
type TwigDo struct{ n *syntax.Node }

// CastTwigDo returns a typed TwigDo wrapper if n has kind syntax.TwigDo.
func CastTwigDo(n *syntax.Node) (TwigDo, bool) {
	if n == nil || n.Kind() != syntax.TwigDo {
		return TwigDo{}, false
	}
	return TwigDo{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigDo) Syntax() *syntax.Node { return x.n }

// TwigEmbed is a typed wrapper around a syntax.TwigEmbed node.
type TwigEmbed struct{ n *syntax.Node }

// CastTwigEmbed returns a typed TwigEmbed wrapper if n has kind syntax.TwigEmbed.
func CastTwigEmbed(n *syntax.Node) (TwigEmbed, bool) {
	if n == nil || n.Kind() != syntax.TwigEmbed {
		return TwigEmbed{}, false
	}
	return TwigEmbed{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEmbed) Syntax() *syntax.Node { return x.n }

// TwigEmbedStartingBlock is a typed wrapper around a syntax.TwigEmbedStartingBlock node.
type TwigEmbedStartingBlock struct{ n *syntax.Node }

// CastTwigEmbedStartingBlock returns a typed TwigEmbedStartingBlock wrapper if n has kind syntax.TwigEmbedStartingBlock.
func CastTwigEmbedStartingBlock(n *syntax.Node) (TwigEmbedStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEmbedStartingBlock {
		return TwigEmbedStartingBlock{}, false
	}
	return TwigEmbedStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEmbedStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigEmbedEndingBlock is a typed wrapper around a syntax.TwigEmbedEndingBlock node.
type TwigEmbedEndingBlock struct{ n *syntax.Node }

// CastTwigEmbedEndingBlock returns a typed TwigEmbedEndingBlock wrapper if n has kind syntax.TwigEmbedEndingBlock.
func CastTwigEmbedEndingBlock(n *syntax.Node) (TwigEmbedEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigEmbedEndingBlock {
		return TwigEmbedEndingBlock{}, false
	}
	return TwigEmbedEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigEmbedEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigFlush is a typed wrapper around a syntax.TwigFlush node.
type TwigFlush struct{ n *syntax.Node }

// CastTwigFlush returns a typed TwigFlush wrapper if n has kind syntax.TwigFlush.
func CastTwigFlush(n *syntax.Node) (TwigFlush, bool) {
	if n == nil || n.Kind() != syntax.TwigFlush {
		return TwigFlush{}, false
	}
	return TwigFlush{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigFlush) Syntax() *syntax.Node { return x.n }

// TwigFrom is a typed wrapper around a syntax.TwigFrom node.
type TwigFrom struct{ n *syntax.Node }

// CastTwigFrom returns a typed TwigFrom wrapper if n has kind syntax.TwigFrom.
func CastTwigFrom(n *syntax.Node) (TwigFrom, bool) {
	if n == nil || n.Kind() != syntax.TwigFrom {
		return TwigFrom{}, false
	}
	return TwigFrom{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigFrom) Syntax() *syntax.Node { return x.n }

// TwigImport is a typed wrapper around a syntax.TwigImport node.
type TwigImport struct{ n *syntax.Node }

// CastTwigImport returns a typed TwigImport wrapper if n has kind syntax.TwigImport.
func CastTwigImport(n *syntax.Node) (TwigImport, bool) {
	if n == nil || n.Kind() != syntax.TwigImport {
		return TwigImport{}, false
	}
	return TwigImport{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigImport) Syntax() *syntax.Node { return x.n }

// TwigSandbox is a typed wrapper around a syntax.TwigSandbox node.
type TwigSandbox struct{ n *syntax.Node }

// CastTwigSandbox returns a typed TwigSandbox wrapper if n has kind syntax.TwigSandbox.
func CastTwigSandbox(n *syntax.Node) (TwigSandbox, bool) {
	if n == nil || n.Kind() != syntax.TwigSandbox {
		return TwigSandbox{}, false
	}
	return TwigSandbox{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigSandbox) Syntax() *syntax.Node { return x.n }

// TwigSandboxStartingBlock is a typed wrapper around a syntax.TwigSandboxStartingBlock node.
type TwigSandboxStartingBlock struct{ n *syntax.Node }

// CastTwigSandboxStartingBlock returns a typed TwigSandboxStartingBlock wrapper if n has kind syntax.TwigSandboxStartingBlock.
func CastTwigSandboxStartingBlock(n *syntax.Node) (TwigSandboxStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigSandboxStartingBlock {
		return TwigSandboxStartingBlock{}, false
	}
	return TwigSandboxStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigSandboxStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigSandboxEndingBlock is a typed wrapper around a syntax.TwigSandboxEndingBlock node.
type TwigSandboxEndingBlock struct{ n *syntax.Node }

// CastTwigSandboxEndingBlock returns a typed TwigSandboxEndingBlock wrapper if n has kind syntax.TwigSandboxEndingBlock.
func CastTwigSandboxEndingBlock(n *syntax.Node) (TwigSandboxEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigSandboxEndingBlock {
		return TwigSandboxEndingBlock{}, false
	}
	return TwigSandboxEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigSandboxEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigVerbatim is a typed wrapper around a syntax.TwigVerbatim node.
type TwigVerbatim struct{ n *syntax.Node }

// CastTwigVerbatim returns a typed TwigVerbatim wrapper if n has kind syntax.TwigVerbatim.
func CastTwigVerbatim(n *syntax.Node) (TwigVerbatim, bool) {
	if n == nil || n.Kind() != syntax.TwigVerbatim {
		return TwigVerbatim{}, false
	}
	return TwigVerbatim{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigVerbatim) Syntax() *syntax.Node { return x.n }

// TwigVerbatimStartingBlock is a typed wrapper around a syntax.TwigVerbatimStartingBlock node.
type TwigVerbatimStartingBlock struct{ n *syntax.Node }

// CastTwigVerbatimStartingBlock returns a typed TwigVerbatimStartingBlock wrapper if n has kind syntax.TwigVerbatimStartingBlock.
func CastTwigVerbatimStartingBlock(n *syntax.Node) (TwigVerbatimStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigVerbatimStartingBlock {
		return TwigVerbatimStartingBlock{}, false
	}
	return TwigVerbatimStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigVerbatimStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigVerbatimEndingBlock is a typed wrapper around a syntax.TwigVerbatimEndingBlock node.
type TwigVerbatimEndingBlock struct{ n *syntax.Node }

// CastTwigVerbatimEndingBlock returns a typed TwigVerbatimEndingBlock wrapper if n has kind syntax.TwigVerbatimEndingBlock.
func CastTwigVerbatimEndingBlock(n *syntax.Node) (TwigVerbatimEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigVerbatimEndingBlock {
		return TwigVerbatimEndingBlock{}, false
	}
	return TwigVerbatimEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigVerbatimEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigMacro is a typed wrapper around a syntax.TwigMacro node.
type TwigMacro struct{ n *syntax.Node }

// CastTwigMacro returns a typed TwigMacro wrapper if n has kind syntax.TwigMacro.
func CastTwigMacro(n *syntax.Node) (TwigMacro, bool) {
	if n == nil || n.Kind() != syntax.TwigMacro {
		return TwigMacro{}, false
	}
	return TwigMacro{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigMacro) Syntax() *syntax.Node { return x.n }

// TwigMacroStartingBlock is a typed wrapper around a syntax.TwigMacroStartingBlock node.
type TwigMacroStartingBlock struct{ n *syntax.Node }

// CastTwigMacroStartingBlock returns a typed TwigMacroStartingBlock wrapper if n has kind syntax.TwigMacroStartingBlock.
func CastTwigMacroStartingBlock(n *syntax.Node) (TwigMacroStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigMacroStartingBlock {
		return TwigMacroStartingBlock{}, false
	}
	return TwigMacroStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigMacroStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigMacroEndingBlock is a typed wrapper around a syntax.TwigMacroEndingBlock node.
type TwigMacroEndingBlock struct{ n *syntax.Node }

// CastTwigMacroEndingBlock returns a typed TwigMacroEndingBlock wrapper if n has kind syntax.TwigMacroEndingBlock.
func CastTwigMacroEndingBlock(n *syntax.Node) (TwigMacroEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigMacroEndingBlock {
		return TwigMacroEndingBlock{}, false
	}
	return TwigMacroEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigMacroEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigWith is a typed wrapper around a syntax.TwigWith node.
type TwigWith struct{ n *syntax.Node }

// CastTwigWith returns a typed TwigWith wrapper if n has kind syntax.TwigWith.
func CastTwigWith(n *syntax.Node) (TwigWith, bool) {
	if n == nil || n.Kind() != syntax.TwigWith {
		return TwigWith{}, false
	}
	return TwigWith{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigWith) Syntax() *syntax.Node { return x.n }

// TwigWithStartingBlock is a typed wrapper around a syntax.TwigWithStartingBlock node.
type TwigWithStartingBlock struct{ n *syntax.Node }

// CastTwigWithStartingBlock returns a typed TwigWithStartingBlock wrapper if n has kind syntax.TwigWithStartingBlock.
func CastTwigWithStartingBlock(n *syntax.Node) (TwigWithStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigWithStartingBlock {
		return TwigWithStartingBlock{}, false
	}
	return TwigWithStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigWithStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigWithEndingBlock is a typed wrapper around a syntax.TwigWithEndingBlock node.
type TwigWithEndingBlock struct{ n *syntax.Node }

// CastTwigWithEndingBlock returns a typed TwigWithEndingBlock wrapper if n has kind syntax.TwigWithEndingBlock.
func CastTwigWithEndingBlock(n *syntax.Node) (TwigWithEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigWithEndingBlock {
		return TwigWithEndingBlock{}, false
	}
	return TwigWithEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigWithEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigCache is a typed wrapper around a syntax.TwigCache node.
type TwigCache struct{ n *syntax.Node }

// CastTwigCache returns a typed TwigCache wrapper if n has kind syntax.TwigCache.
func CastTwigCache(n *syntax.Node) (TwigCache, bool) {
	if n == nil || n.Kind() != syntax.TwigCache {
		return TwigCache{}, false
	}
	return TwigCache{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigCache) Syntax() *syntax.Node { return x.n }

// TwigCacheTTL is a typed wrapper around a syntax.TwigCacheTtl node.
type TwigCacheTTL struct{ n *syntax.Node }

// CastTwigCacheTTL returns a typed TwigCacheTTL wrapper if n has kind syntax.TwigCacheTtl.
func CastTwigCacheTTL(n *syntax.Node) (TwigCacheTTL, bool) {
	if n == nil || n.Kind() != syntax.TwigCacheTtl {
		return TwigCacheTTL{}, false
	}
	return TwigCacheTTL{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigCacheTTL) Syntax() *syntax.Node { return x.n }

// TwigCacheTags is a typed wrapper around a syntax.TwigCacheTags node.
type TwigCacheTags struct{ n *syntax.Node }

// CastTwigCacheTags returns a typed TwigCacheTags wrapper if n has kind syntax.TwigCacheTags.
func CastTwigCacheTags(n *syntax.Node) (TwigCacheTags, bool) {
	if n == nil || n.Kind() != syntax.TwigCacheTags {
		return TwigCacheTags{}, false
	}
	return TwigCacheTags{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigCacheTags) Syntax() *syntax.Node { return x.n }

// TwigCacheStartingBlock is a typed wrapper around a syntax.TwigCacheStartingBlock node.
type TwigCacheStartingBlock struct{ n *syntax.Node }

// CastTwigCacheStartingBlock returns a typed TwigCacheStartingBlock wrapper if n has kind syntax.TwigCacheStartingBlock.
func CastTwigCacheStartingBlock(n *syntax.Node) (TwigCacheStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigCacheStartingBlock {
		return TwigCacheStartingBlock{}, false
	}
	return TwigCacheStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigCacheStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigCacheEndingBlock is a typed wrapper around a syntax.TwigCacheEndingBlock node.
type TwigCacheEndingBlock struct{ n *syntax.Node }

// CastTwigCacheEndingBlock returns a typed TwigCacheEndingBlock wrapper if n has kind syntax.TwigCacheEndingBlock.
func CastTwigCacheEndingBlock(n *syntax.Node) (TwigCacheEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigCacheEndingBlock {
		return TwigCacheEndingBlock{}, false
	}
	return TwigCacheEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigCacheEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigProps is a typed wrapper around a syntax.TwigProps node.
type TwigProps struct{ n *syntax.Node }

// CastTwigProps returns a typed TwigProps wrapper if n has kind syntax.TwigProps.
func CastTwigProps(n *syntax.Node) (TwigProps, bool) {
	if n == nil || n.Kind() != syntax.TwigProps {
		return TwigProps{}, false
	}
	return TwigProps{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigProps) Syntax() *syntax.Node { return x.n }

// TwigPropDeclaration is a typed wrapper around a syntax.TwigPropDeclaration node.
type TwigPropDeclaration struct{ n *syntax.Node }

// CastTwigPropDeclaration returns a typed TwigPropDeclaration wrapper if n has kind syntax.TwigPropDeclaration.
func CastTwigPropDeclaration(n *syntax.Node) (TwigPropDeclaration, bool) {
	if n == nil || n.Kind() != syntax.TwigPropDeclaration {
		return TwigPropDeclaration{}, false
	}
	return TwigPropDeclaration{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigPropDeclaration) Syntax() *syntax.Node { return x.n }

// TwigComponent is a typed wrapper around a syntax.TwigComponent node.
type TwigComponent struct{ n *syntax.Node }

// CastTwigComponent returns a typed TwigComponent wrapper if n has kind syntax.TwigComponent.
func CastTwigComponent(n *syntax.Node) (TwigComponent, bool) {
	if n == nil || n.Kind() != syntax.TwigComponent {
		return TwigComponent{}, false
	}
	return TwigComponent{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigComponent) Syntax() *syntax.Node { return x.n }

// TwigComponentStartingBlock is a typed wrapper around a syntax.TwigComponentStartingBlock node.
type TwigComponentStartingBlock struct{ n *syntax.Node }

// CastTwigComponentStartingBlock returns a typed TwigComponentStartingBlock wrapper if n has kind syntax.TwigComponentStartingBlock.
func CastTwigComponentStartingBlock(n *syntax.Node) (TwigComponentStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigComponentStartingBlock {
		return TwigComponentStartingBlock{}, false
	}
	return TwigComponentStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigComponentStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigComponentEndingBlock is a typed wrapper around a syntax.TwigComponentEndingBlock node.
type TwigComponentEndingBlock struct{ n *syntax.Node }

// CastTwigComponentEndingBlock returns a typed TwigComponentEndingBlock wrapper if n has kind syntax.TwigComponentEndingBlock.
func CastTwigComponentEndingBlock(n *syntax.Node) (TwigComponentEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigComponentEndingBlock {
		return TwigComponentEndingBlock{}, false
	}
	return TwigComponentEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigComponentEndingBlock) Syntax() *syntax.Node { return x.n }

// TwigTrans is a typed wrapper around a syntax.TwigTrans node.
type TwigTrans struct{ n *syntax.Node }

// CastTwigTrans returns a typed TwigTrans wrapper if n has kind syntax.TwigTrans.
func CastTwigTrans(n *syntax.Node) (TwigTrans, bool) {
	if n == nil || n.Kind() != syntax.TwigTrans {
		return TwigTrans{}, false
	}
	return TwigTrans{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigTrans) Syntax() *syntax.Node { return x.n }

// TwigTransStartingBlock is a typed wrapper around a syntax.TwigTransStartingBlock node.
type TwigTransStartingBlock struct{ n *syntax.Node }

// CastTwigTransStartingBlock returns a typed TwigTransStartingBlock wrapper if n has kind syntax.TwigTransStartingBlock.
func CastTwigTransStartingBlock(n *syntax.Node) (TwigTransStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigTransStartingBlock {
		return TwigTransStartingBlock{}, false
	}
	return TwigTransStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigTransStartingBlock) Syntax() *syntax.Node { return x.n }

// TwigTransEndingBlock is a typed wrapper around a syntax.TwigTransEndingBlock node.
type TwigTransEndingBlock struct{ n *syntax.Node }

// CastTwigTransEndingBlock returns a typed TwigTransEndingBlock wrapper if n has kind syntax.TwigTransEndingBlock.
func CastTwigTransEndingBlock(n *syntax.Node) (TwigTransEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.TwigTransEndingBlock {
		return TwigTransEndingBlock{}, false
	}
	return TwigTransEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x TwigTransEndingBlock) Syntax() *syntax.Node { return x.n }

// ShopwareTwigExtends is a typed wrapper around a syntax.ShopwareTwigSwExtends node.
type ShopwareTwigExtends struct{ n *syntax.Node }

// CastShopwareTwigExtends returns a typed ShopwareTwigExtends wrapper if n has kind syntax.ShopwareTwigSwExtends.
func CastShopwareTwigExtends(n *syntax.Node) (ShopwareTwigExtends, bool) {
	if n == nil || n.Kind() != syntax.ShopwareTwigSwExtends {
		return ShopwareTwigExtends{}, false
	}
	return ShopwareTwigExtends{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareTwigExtends) Syntax() *syntax.Node { return x.n }

// ShopwareTwigInclude is a typed wrapper around a syntax.ShopwareTwigSwInclude node.
type ShopwareTwigInclude struct{ n *syntax.Node }

// CastShopwareTwigInclude returns a typed ShopwareTwigInclude wrapper if n has kind syntax.ShopwareTwigSwInclude.
func CastShopwareTwigInclude(n *syntax.Node) (ShopwareTwigInclude, bool) {
	if n == nil || n.Kind() != syntax.ShopwareTwigSwInclude {
		return ShopwareTwigInclude{}, false
	}
	return ShopwareTwigInclude{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareTwigInclude) Syntax() *syntax.Node { return x.n }

// ShopwareSilentFeatureCall is a typed wrapper around a syntax.ShopwareSilentFeatureCall node.
type ShopwareSilentFeatureCall struct{ n *syntax.Node }

// CastShopwareSilentFeatureCall returns a typed ShopwareSilentFeatureCall wrapper if n has kind syntax.ShopwareSilentFeatureCall.
func CastShopwareSilentFeatureCall(n *syntax.Node) (ShopwareSilentFeatureCall, bool) {
	if n == nil || n.Kind() != syntax.ShopwareSilentFeatureCall {
		return ShopwareSilentFeatureCall{}, false
	}
	return ShopwareSilentFeatureCall{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareSilentFeatureCall) Syntax() *syntax.Node { return x.n }

// ShopwareSilentFeatureCallStartingBlock is a typed wrapper around a syntax.ShopwareSilentFeatureCallStartingBlock node.
type ShopwareSilentFeatureCallStartingBlock struct{ n *syntax.Node }

// CastShopwareSilentFeatureCallStartingBlock returns a typed ShopwareSilentFeatureCallStartingBlock wrapper if n has kind syntax.ShopwareSilentFeatureCallStartingBlock.
func CastShopwareSilentFeatureCallStartingBlock(n *syntax.Node) (ShopwareSilentFeatureCallStartingBlock, bool) {
	if n == nil || n.Kind() != syntax.ShopwareSilentFeatureCallStartingBlock {
		return ShopwareSilentFeatureCallStartingBlock{}, false
	}
	return ShopwareSilentFeatureCallStartingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareSilentFeatureCallStartingBlock) Syntax() *syntax.Node { return x.n }

// ShopwareSilentFeatureCallEndingBlock is a typed wrapper around a syntax.ShopwareSilentFeatureCallEndingBlock node.
type ShopwareSilentFeatureCallEndingBlock struct{ n *syntax.Node }

// CastShopwareSilentFeatureCallEndingBlock returns a typed ShopwareSilentFeatureCallEndingBlock wrapper if n has kind syntax.ShopwareSilentFeatureCallEndingBlock.
func CastShopwareSilentFeatureCallEndingBlock(n *syntax.Node) (ShopwareSilentFeatureCallEndingBlock, bool) {
	if n == nil || n.Kind() != syntax.ShopwareSilentFeatureCallEndingBlock {
		return ShopwareSilentFeatureCallEndingBlock{}, false
	}
	return ShopwareSilentFeatureCallEndingBlock{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareSilentFeatureCallEndingBlock) Syntax() *syntax.Node { return x.n }

// ShopwareReturn is a typed wrapper around a syntax.ShopwareReturn node.
type ShopwareReturn struct{ n *syntax.Node }

// CastShopwareReturn returns a typed ShopwareReturn wrapper if n has kind syntax.ShopwareReturn.
func CastShopwareReturn(n *syntax.Node) (ShopwareReturn, bool) {
	if n == nil || n.Kind() != syntax.ShopwareReturn {
		return ShopwareReturn{}, false
	}
	return ShopwareReturn{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareReturn) Syntax() *syntax.Node { return x.n }

// ShopwareIcon is a typed wrapper around a syntax.ShopwareIcon node.
type ShopwareIcon struct{ n *syntax.Node }

// CastShopwareIcon returns a typed ShopwareIcon wrapper if n has kind syntax.ShopwareIcon.
func CastShopwareIcon(n *syntax.Node) (ShopwareIcon, bool) {
	if n == nil || n.Kind() != syntax.ShopwareIcon {
		return ShopwareIcon{}, false
	}
	return ShopwareIcon{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareIcon) Syntax() *syntax.Node { return x.n }

// ShopwareIconStyle is a typed wrapper around a syntax.ShopwareIconStyle node.
type ShopwareIconStyle struct{ n *syntax.Node }

// CastShopwareIconStyle returns a typed ShopwareIconStyle wrapper if n has kind syntax.ShopwareIconStyle.
func CastShopwareIconStyle(n *syntax.Node) (ShopwareIconStyle, bool) {
	if n == nil || n.Kind() != syntax.ShopwareIconStyle {
		return ShopwareIconStyle{}, false
	}
	return ShopwareIconStyle{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareIconStyle) Syntax() *syntax.Node { return x.n }

// ShopwareThumbnails is a typed wrapper around a syntax.ShopwareThumbnails node.
type ShopwareThumbnails struct{ n *syntax.Node }

// CastShopwareThumbnails returns a typed ShopwareThumbnails wrapper if n has kind syntax.ShopwareThumbnails.
func CastShopwareThumbnails(n *syntax.Node) (ShopwareThumbnails, bool) {
	if n == nil || n.Kind() != syntax.ShopwareThumbnails {
		return ShopwareThumbnails{}, false
	}
	return ShopwareThumbnails{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareThumbnails) Syntax() *syntax.Node { return x.n }

// ShopwareThumbnailsWith is a typed wrapper around a syntax.ShopwareThumbnailsWith node.
type ShopwareThumbnailsWith struct{ n *syntax.Node }

// CastShopwareThumbnailsWith returns a typed ShopwareThumbnailsWith wrapper if n has kind syntax.ShopwareThumbnailsWith.
func CastShopwareThumbnailsWith(n *syntax.Node) (ShopwareThumbnailsWith, bool) {
	if n == nil || n.Kind() != syntax.ShopwareThumbnailsWith {
		return ShopwareThumbnailsWith{}, false
	}
	return ShopwareThumbnailsWith{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x ShopwareThumbnailsWith) Syntax() *syntax.Node { return x.n }

// HtmlDoctype is a typed wrapper around a syntax.HtmlDoctype node.
type HtmlDoctype struct{ n *syntax.Node }

// CastHtmlDoctype returns a typed HtmlDoctype wrapper if n has kind syntax.HtmlDoctype.
func CastHtmlDoctype(n *syntax.Node) (HtmlDoctype, bool) {
	if n == nil || n.Kind() != syntax.HtmlDoctype {
		return HtmlDoctype{}, false
	}
	return HtmlDoctype{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlDoctype) Syntax() *syntax.Node { return x.n }

// HtmlAttributeList is a typed wrapper around a syntax.HtmlAttributeList node.
type HtmlAttributeList struct{ n *syntax.Node }

// CastHtmlAttributeList returns a typed HtmlAttributeList wrapper if n has kind syntax.HtmlAttributeList.
func CastHtmlAttributeList(n *syntax.Node) (HtmlAttributeList, bool) {
	if n == nil || n.Kind() != syntax.HtmlAttributeList {
		return HtmlAttributeList{}, false
	}
	return HtmlAttributeList{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlAttributeList) Syntax() *syntax.Node { return x.n }

// HtmlAttribute is a typed wrapper around a syntax.HtmlAttribute node.
type HtmlAttribute struct{ n *syntax.Node }

// CastHtmlAttribute returns a typed HtmlAttribute wrapper if n has kind syntax.HtmlAttribute.
func CastHtmlAttribute(n *syntax.Node) (HtmlAttribute, bool) {
	if n == nil || n.Kind() != syntax.HtmlAttribute {
		return HtmlAttribute{}, false
	}
	return HtmlAttribute{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlAttribute) Syntax() *syntax.Node { return x.n }

// HtmlString is a typed wrapper around a syntax.HtmlString node.
type HtmlString struct{ n *syntax.Node }

// CastHtmlString returns a typed HtmlString wrapper if n has kind syntax.HtmlString.
func CastHtmlString(n *syntax.Node) (HtmlString, bool) {
	if n == nil || n.Kind() != syntax.HtmlString {
		return HtmlString{}, false
	}
	return HtmlString{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlString) Syntax() *syntax.Node { return x.n }

// HtmlStringInner is a typed wrapper around a syntax.HtmlStringInner node.
type HtmlStringInner struct{ n *syntax.Node }

// CastHtmlStringInner returns a typed HtmlStringInner wrapper if n has kind syntax.HtmlStringInner.
func CastHtmlStringInner(n *syntax.Node) (HtmlStringInner, bool) {
	if n == nil || n.Kind() != syntax.HtmlStringInner {
		return HtmlStringInner{}, false
	}
	return HtmlStringInner{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlStringInner) Syntax() *syntax.Node { return x.n }

// HtmlText is a typed wrapper around a syntax.HtmlText node.
type HtmlText struct{ n *syntax.Node }

// CastHtmlText returns a typed HtmlText wrapper if n has kind syntax.HtmlText.
func CastHtmlText(n *syntax.Node) (HtmlText, bool) {
	if n == nil || n.Kind() != syntax.HtmlText {
		return HtmlText{}, false
	}
	return HtmlText{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlText) Syntax() *syntax.Node { return x.n }

// HtmlRawText is a typed wrapper around a syntax.HtmlRawText node.
type HtmlRawText struct{ n *syntax.Node }

// CastHtmlRawText returns a typed HtmlRawText wrapper if n has kind syntax.HtmlRawText.
func CastHtmlRawText(n *syntax.Node) (HtmlRawText, bool) {
	if n == nil || n.Kind() != syntax.HtmlRawText {
		return HtmlRawText{}, false
	}
	return HtmlRawText{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlRawText) Syntax() *syntax.Node { return x.n }

// HtmlComment is a typed wrapper around a syntax.HtmlComment node.
type HtmlComment struct{ n *syntax.Node }

// CastHtmlComment returns a typed HtmlComment wrapper if n has kind syntax.HtmlComment.
func CastHtmlComment(n *syntax.Node) (HtmlComment, bool) {
	if n == nil || n.Kind() != syntax.HtmlComment {
		return HtmlComment{}, false
	}
	return HtmlComment{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlComment) Syntax() *syntax.Node { return x.n }

// HtmlTag is a typed wrapper around a syntax.HtmlTag node.
type HtmlTag struct{ n *syntax.Node }

// CastHtmlTag returns a typed HtmlTag wrapper if n has kind syntax.HtmlTag.
func CastHtmlTag(n *syntax.Node) (HtmlTag, bool) {
	if n == nil || n.Kind() != syntax.HtmlTag {
		return HtmlTag{}, false
	}
	return HtmlTag{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlTag) Syntax() *syntax.Node { return x.n }

// HtmlStartingTag is a typed wrapper around a syntax.HtmlStartingTag node.
type HtmlStartingTag struct{ n *syntax.Node }

// CastHtmlStartingTag returns a typed HtmlStartingTag wrapper if n has kind syntax.HtmlStartingTag.
func CastHtmlStartingTag(n *syntax.Node) (HtmlStartingTag, bool) {
	if n == nil || n.Kind() != syntax.HtmlStartingTag {
		return HtmlStartingTag{}, false
	}
	return HtmlStartingTag{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlStartingTag) Syntax() *syntax.Node { return x.n }

// HtmlEndingTag is a typed wrapper around a syntax.HtmlEndingTag node.
type HtmlEndingTag struct{ n *syntax.Node }

// CastHtmlEndingTag returns a typed HtmlEndingTag wrapper if n has kind syntax.HtmlEndingTag.
func CastHtmlEndingTag(n *syntax.Node) (HtmlEndingTag, bool) {
	if n == nil || n.Kind() != syntax.HtmlEndingTag {
		return HtmlEndingTag{}, false
	}
	return HtmlEndingTag{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x HtmlEndingTag) Syntax() *syntax.Node { return x.n }

// LudtwigDirectiveFileIgnore is a typed wrapper around a syntax.LudtwigDirectiveFileIgnore node.
type LudtwigDirectiveFileIgnore struct{ n *syntax.Node }

// CastLudtwigDirectiveFileIgnore returns a typed LudtwigDirectiveFileIgnore wrapper if n has kind syntax.LudtwigDirectiveFileIgnore.
func CastLudtwigDirectiveFileIgnore(n *syntax.Node) (LudtwigDirectiveFileIgnore, bool) {
	if n == nil || n.Kind() != syntax.LudtwigDirectiveFileIgnore {
		return LudtwigDirectiveFileIgnore{}, false
	}
	return LudtwigDirectiveFileIgnore{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x LudtwigDirectiveFileIgnore) Syntax() *syntax.Node { return x.n }

// LudtwigDirectiveIgnore is a typed wrapper around a syntax.LudtwigDirectiveIgnore node.
type LudtwigDirectiveIgnore struct{ n *syntax.Node }

// CastLudtwigDirectiveIgnore returns a typed LudtwigDirectiveIgnore wrapper if n has kind syntax.LudtwigDirectiveIgnore.
func CastLudtwigDirectiveIgnore(n *syntax.Node) (LudtwigDirectiveIgnore, bool) {
	if n == nil || n.Kind() != syntax.LudtwigDirectiveIgnore {
		return LudtwigDirectiveIgnore{}, false
	}
	return LudtwigDirectiveIgnore{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x LudtwigDirectiveIgnore) Syntax() *syntax.Node { return x.n }

// LudtwigDirectiveRuleList is a typed wrapper around a syntax.LudtwigDirectiveRuleList node.
type LudtwigDirectiveRuleList struct{ n *syntax.Node }

// CastLudtwigDirectiveRuleList returns a typed LudtwigDirectiveRuleList wrapper if n has kind syntax.LudtwigDirectiveRuleList.
func CastLudtwigDirectiveRuleList(n *syntax.Node) (LudtwigDirectiveRuleList, bool) {
	if n == nil || n.Kind() != syntax.LudtwigDirectiveRuleList {
		return LudtwigDirectiveRuleList{}, false
	}
	return LudtwigDirectiveRuleList{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x LudtwigDirectiveRuleList) Syntax() *syntax.Node { return x.n }

// Error is a typed wrapper around a syntax.Error node.
type Error struct{ n *syntax.Node }

// CastError returns a typed Error wrapper if n has kind syntax.Error.
func CastError(n *syntax.Node) (Error, bool) {
	if n == nil || n.Kind() != syntax.Error {
		return Error{}, false
	}
	return Error{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x Error) Syntax() *syntax.Node { return x.n }

// Root is a typed wrapper around a syntax.Root node.
type Root struct{ n *syntax.Node }

// CastRoot returns a typed Root wrapper if n has kind syntax.Root.
func CastRoot(n *syntax.Node) (Root, bool) {
	if n == nil || n.Kind() != syntax.Root {
		return Root{}, false
	}
	return Root{n: n}, true
}

// Syntax returns the underlying syntax node.
func (x Root) Syntax() *syntax.Node { return x.n }
