package app

import (
	"github.com/shopware/shopware-lsp/internal/lsp"
	"github.com/shopware/shopware-lsp/internal/lsp/definition"
	"github.com/shopware/shopware-lsp/internal/lsp/phpsemantic"
)

func registerDefinitionProviders(server *lsp.Server, root string, phpFeatures *phpsemantic.Provider, services workspaceServices) {
	if !server.FrameworkPresentation() {
		server.RegisterDefinitionProvider(phpFeatures)
		server.RegisterImplementationProvider(phpFeatures)
		server.RegisterTypeHierarchyProvider(phpFeatures)
	}
	server.RegisterDefinitionProvider(
		definition.NewContainerConstantDefinitionProvider(services.php),
	)
	server.RegisterDefinitionProvider(
		definition.NewHttpClientDefinitionProvider(services.php),
	)
	server.RegisterDefinitionProvider(
		definition.NewConsoleHelperDefinitionProvider(services.php),
	)
	server.RegisterDefinitionProvider(definition.NewConsoleDefinitionProvider(
		services.console,
	))
	server.RegisterDefinitionProvider(definition.NewDoctrineDefinitionProvider(
		services.doctrine,
		services.php,
	))
	server.RegisterDefinitionProvider(definition.NewAssetDefinitionProvider(
		services.assets,
		services.php,
	))
	server.RegisterDefinitionProvider(
		definition.NewStimulusDefinitionProvider(services.stimulus),
	)
	if server.DomainEnabled("scss") {
		server.RegisterDefinitionProvider(
			definition.NewStyleClassDefinitionProvider(services.styles),
		)
	}
	server.RegisterDefinitionProvider(definition.NewEventDefinitionProvider(
		services.events,
		services.php,
		services.services,
	))
	server.RegisterDefinitionProvider(
		definition.NewMessengerDefinitionProvider(
			services.php,
			services.messenger,
		),
	)
	server.RegisterDefinitionProvider(
		definition.NewEnvironmentDefinitionProvider(
			services.environment,
		),
	)
	server.RegisterDefinitionProvider(definition.NewFormDefinitionProvider(
		services.forms,
		services.php,
	))
	server.RegisterDefinitionProvider(definition.NewSecurityDefinitionProvider(
		services.security,
	))
	server.RegisterDefinitionProvider(
		definition.NewSymfonyConfigDefinitionProvider(
			services.configuration,
		),
	)
	server.RegisterDefinitionProvider(definition.NewSerializerDefinitionProvider(
		services.serializer,
		services.php,
	))
	server.RegisterDefinitionProvider(definition.NewValidationDefinitionProvider())
	server.RegisterDefinitionProvider(
		definition.NewTwigEnumDefinitionProvider(services.php),
	)
	server.RegisterDefinitionProvider(
		definition.NewTwigConstantDefinitionProvider(
			services.php,
			services.twig,
		),
	)
	server.RegisterDefinitionProvider(definition.NewServiceXMLDefinitionProvider(services.services, services.php))
	server.RegisterDefinitionProvider(definition.NewTwigMacroDefinitionProvider(
		services.twig,
	))
	server.RegisterDefinitionProvider(
		definition.NewTwigComponentDefinitionProvider(
			services.twigComponents,
			services.php,
		),
	)
	server.RegisterDefinitionProvider(
		definition.NewLiveComponentEventDefinitionProvider(
			services.twigComponents,
		),
	)
	server.RegisterDefinitionProvider(
		definition.NewTwigIncludeParameterDefinitionProvider(
			services.twig,
			services.php,
		),
	)
	server.RegisterDefinitionProvider(
		definition.NewTwigRenderBlockDefinitionProvider(
			services.twig,
			services.php,
		),
	)
	server.RegisterDefinitionProvider(definition.NewTwigDefinitionProvider(
		root,
		services.twig,
		services.extensions,
		services.php,
	))
	server.RegisterDefinitionProvider(definition.NewRouteDefinitionProvider(
		services.routes,
		services.php,
	))
	server.RegisterDefinitionProvider(definition.NewControllerDefinitionProvider(services.services, services.php))
	server.RegisterDefinitionProvider(definition.NewTranslationDefinitionProvider(services.translations, services.php))
	server.RegisterDefinitionProvider(definition.NewSnippetDefinitionProvider(services.snippets))
	server.RegisterDefinitionProvider(definition.NewFeatureDefinitionProvider(services.features))
	server.RegisterDefinitionProvider(definition.NewDALDefinitionProvider(services.dal))
	server.RegisterDefinitionProvider(definition.NewSystemConfigDefinitionProvider(services.systemConfig, services.php))
	server.RegisterDefinitionProvider(definition.NewThemeDefinitionProvider(services.theme))
	if server.DomainEnabled("administration") {
		server.RegisterDefinitionProvider(definition.NewAdminDefinitionProvider(services.admin))
	}
}
