package app

import (
	"github.com/shopware/shopware-lsp/internal/lsp"
	"github.com/shopware/shopware-lsp/internal/lsp/completion"
	"github.com/shopware/shopware-lsp/internal/lsp/phpsemantic"
)

func registerCompletionProviders(server *lsp.Server, root string, phpFeatures *phpsemantic.Provider, services workspaceServices) {
	if !server.FrameworkPresentation() {
		server.RegisterCompletionProvider(phpFeatures)
	}
	server.RegisterCompletionProvider(
		completion.NewPHPAttributeCompletionProvider(services.php),
	)
	server.RegisterCompletionProvider(
		completion.NewResponseConstantCompletionProvider(
			services.php,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewHttpClientCompletionProvider(services.php),
	)
	server.RegisterCompletionProvider(
		completion.NewContainerConstantCompletionProvider(services.php),
	)
	server.RegisterCompletionProvider(
		completion.NewConsoleHelperCompletionProvider(services.php),
	)
	server.RegisterCompletionProvider(completion.NewConsoleCompletionProvider(
		services.console,
	))
	server.RegisterCompletionProvider(completion.NewDoctrineCompletionProvider(
		services.doctrine,
		services.php,
	))
	server.RegisterCompletionProvider(completion.NewAssetCompletionProvider(
		services.assets,
		services.php,
	))
	server.RegisterCompletionProvider(
		completion.NewStimulusCompletionProvider(services.stimulus),
	)
	server.RegisterCompletionProvider(completion.NewEventCompletionProvider(
		services.events,
		services.php,
		services.services,
	))
	server.RegisterCompletionProvider(
		completion.NewMessengerCompletionProvider(
			services.php,
			services.messenger,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewEnvironmentCompletionProvider(
			services.environment,
		),
	)
	server.RegisterCompletionProvider(completion.NewFormCompletionProvider(
		services.forms,
		services.php,
	))
	server.RegisterCompletionProvider(completion.NewSecurityCompletionProvider(
		services.security,
	))
	server.RegisterCompletionProvider(
		completion.NewSymfonyConfigCompletionProvider(
			services.configuration,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewYAMLServiceAuthoringCompletionProvider(
			services.php.Project(),
		),
	)
	server.RegisterCompletionProvider(
		completion.NewYAMLRouteAuthoringCompletionProvider(services.routes),
	)
	server.RegisterCompletionProvider(completion.NewValidationCompletionProvider())
	server.RegisterCompletionProvider(completion.NewServiceCompletionProvider(services.services, services.php))
	server.RegisterCompletionProvider(completion.NewTranslationCompletionProvider(services.translations, services.php))
	server.RegisterCompletionProvider(completion.NewTwigMacroCompletionProvider(
		services.twig,
	))
	server.RegisterCompletionProvider(
		completion.NewTwigEnumCompletionProvider(services.php),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigConstantCompletionProvider(
			services.php,
			services.twig,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigComponentCompletionProvider(
			services.twigComponents,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigComponentVariableCompletionProvider(
			services.twigComponents,
			services.php,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigComponentPHPCompletionProvider(),
	)
	server.RegisterCompletionProvider(
		completion.NewLiveComponentEventCompletionProvider(
			services.twigComponents,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigIncludeParameterCompletionProvider(
			services.twig,
			services.php,
		),
	)
	server.RegisterCompletionProvider(
		completion.NewTwigRenderBlockCompletionProvider(
			services.twig,
			services.php,
		),
	)
	twigCompletion := completion.NewTwigCompletionProvider(
		root,
		services.twig,
		services.extensions,
		services.php,
	)
	if server.FrameworkPresentation() {
		twigCompletion.WithoutBuiltinTwigCompletions()
	}
	server.RegisterCompletionProvider(twigCompletion)
	server.RegisterCompletionProvider(
		completion.NewControllerCompletionProvider(
			services.php,
			services.services,
			services.routes,
		),
	)
	server.RegisterCompletionProvider(completion.NewRouteCompletionProvider(services.routes))
	server.RegisterCompletionProvider(
		completion.NewBundleResourceCompletionProvider(services.php, services.paths),
	)
	server.RegisterCompletionProvider(completion.NewSnippetCompletionProvider(services.snippets))
	server.RegisterCompletionProvider(completion.NewFeatureCompletionProvider(services.features))
	server.RegisterCompletionProvider(completion.NewDALCompletionProvider(services.dal))
	server.RegisterCompletionProvider(completion.NewSystemConfigCompletion(services.systemConfig, services.php))
	server.RegisterCompletionProvider(completion.NewThemeCompletionProvider(services.theme))
	if server.DomainEnabled("administration") {
		server.RegisterCompletionProvider(completion.NewAdminCompletionProvider(services.admin))
	}
}
